# Generated by spaday.cem from components.cem.json — do not edit by hand.
from __future__ import annotations

from typing import Any, Literal

from spaday.catalog import ComponentSchema, PropertySchema
from spaday.component import Child, Component

__all__ = ["VegaChart"]


class VegaChart(Component):
    """A responsive Vega or Vega-Lite visualization driven by a declarative specification."""

    tag = "vega-chart"
    schema = ComponentSchema(
        tag="vega-chart",
        class_name="VegaChart",
        summary="A responsive Vega or Vega-Lite visualization driven by a declarative specification.",
        props=(
            PropertySchema(
                name="spec",
                kind="json",
                choices=(),
                default=None,
                description="A Vega or Vega-Lite specification object, or a URL accepted by Vega-Embed.",
            ),
            PropertySchema(
                name="data",
                kind="json",
                choices=(),
                default=None,
                description="Rows keyed by Vega dataset name. Updates use the current Vega view without re-embedding the specification.",
            ),
            PropertySchema(
                name="signals",
                kind="json",
                choices=(),
                default=None,
                description="Values keyed by Vega signal name. Updates use the current Vega view without re-embedding the specification.",
            ),
            PropertySchema(
                name="signal_listeners",
                kind="json",
                choices=(),
                default=None,
                description="Vega signal names re-dispatched through vega-signal events.",
            ),
            PropertySchema(name="options", kind="json", choices=(), default=None, description="Additional serializable Vega-Embed options."),
            PropertySchema(name="renderer", kind="enum", choices=("svg", "canvas"), default="svg", description="The Vega renderer."),
            PropertySchema(name="actions", kind="boolean", choices=(), default="false", description="Whether Vega-Embed shows its action menu."),
        ),
        events=("vega-ready", "vega-update", "vega-signal", "vega-error"),
        slots=(),
    )

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        spec: Any = None,
        data: Any = None,
        signals: Any = None,
        signal_listeners: Any = None,
        options: Any = None,
        renderer: Literal["svg", "canvas"] | None = None,
        actions: bool | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "spec": spec,
                "data": data,
                "signals": signals,
                "signal_listeners": signal_listeners,
                "options": options,
                "renderer": renderer,
                "actions": actions,
            },
            **props,
        )
